# Generated by Django 6.1.1 on 2026-10-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='balance',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='balance_net_7d',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='task_completes_7d',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='user_wallet_balance',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='users_active_7d',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
