from enum import Enum


class OfferwallReason(str, Enum):
    USER_BLOCKED = "USER_BLOCKED"
    HIGH_RECON_RATE = "HIGH_RECON_RATE"
    UNCOMMON_DEMOGRAPHICS = "UNCOMMON_DEMOGRAPHICS"
    UNDER_MINIMUM_AGE = "UNDER_MINIMUM_AGE"
    EXHAUSTED_HIGH_VALUE_SUPPLY = "EXHAUSTED_HIGH_VALUE_SUPPLY"
    ALL_ELIGIBLE_ATTEMPTED = "ALL_ELIGIBLE_ATTEMPTED"
    LOW_CURRENT_SUPPLY = "LOW_CURRENT_SUPPLY"
