# Generated by Django 6.0 on 2025-12-28 16:49

from django.db import migrations, models
from django.contrib.postgres.operations import AddIndexConcurrently


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("thl_django", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveystat",
            name="is_live",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="surveycategory",
            name="strength",
            field=models.FloatField(
                help_text="Relative relevance or confidence (0–1)", null=True
            ),
        ),
        AddIndexConcurrently(
            model_name="surveystat",
            index=models.Index(
                condition=models.Q(("is_live", True)),
                fields=["survey"],
                name="surveystat_live_survey_idx",
            ),
        ),
    ]
