# Generated by Django 6.0 on 2025-12-29 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thl_django', '0003_remove_surveystat_surveystat_live_survey_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveystat',
            name='survey_is_live',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='surveystat',
            name='survey_source',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='surveystat',
            name='survey_survey_id',
            field=models.CharField(max_length=32),
        ),
    ]
