# Generated by Django 6.0 on 2025-12-31 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("thl_django", "0004_alter_surveystat_survey_is_live_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="surveystat",
            name="marketplace_updated_439a2d_idx",
        ),
    ]
