# Generated by Django 6.0 on 2026-01-02 17:38

from django.db import migrations
from django.contrib.postgres.operations import RemoveIndexConcurrently


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('thl_django', '0005_remove_surveystat_marketplace_updated_439a2d_idx'),
    ]

    operations = [
        RemoveIndexConcurrently(
            model_name='thlsession',
            name='thl_session_status_d578b7_idx',
        ),
        RemoveIndexConcurrently(
            model_name='thlsession',
            name='thl_session_status__4c18db_idx',
        ),
        RemoveIndexConcurrently(
            model_name='thlwall',
            name='thl_wall_source_a6d26f_idx',
        ),
        RemoveIndexConcurrently(
            model_name='thlwall',
            name='thl_wall_source_feb05b_idx',
        ),
        RemoveIndexConcurrently(
            model_name='thlwall',
            name='thl_wall_cpi_0481c1_idx',
        ),
    ]
