# Generated by Django 6.0 on 2026-01-02 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("thl_django", "0006_remove_thlsession_thl_session_status_d578b7_idx_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER TABLE marketplace_userquestionanswer SET (
                autovacuum_analyze_scale_factor = 0.01, autovacuum_analyze_threshold = 50000, autovacuum_vacuum_scale_factor = 0.2
            );
            ALTER TABLE ledger_transactionmetadata SET (
                autovacuum_analyze_scale_factor = 0.01, autovacuum_analyze_threshold = 50000, autovacuum_vacuum_scale_factor = 0.2
            );
            ALTER TABLE ledger_entry SET (
                autovacuum_analyze_scale_factor = 0.01, autovacuum_analyze_threshold = 50000, autovacuum_vacuum_scale_factor = 0.2
            );
            ALTER TABLE ledger_transaction SET (
                autovacuum_analyze_scale_factor = 0.01, autovacuum_analyze_threshold = 50000, autovacuum_vacuum_scale_factor = 0.2
            );
            ALTER TABLE userhealth_iphistory SET (
                autovacuum_analyze_scale_factor = 0.01, autovacuum_analyze_threshold = 50000, autovacuum_vacuum_scale_factor = 0.2
            );
            ALTER TABLE marketplace_userprofileknowledgeitem SET (
                autovacuum_analyze_scale_factor = 0.01, autovacuum_analyze_threshold = 50000, autovacuum_vacuum_scale_factor = 0.2
            );
            ALTER TABLE userhealth_auditlog SET (
                autovacuum_analyze_scale_factor = 0.01, autovacuum_analyze_threshold = 50000, autovacuum_vacuum_scale_factor = 0.2
            );
            ALTER TABLE thl_ipinformation SET (
                autovacuum_analyze_scale_factor = 0.01, autovacuum_analyze_threshold = 50000, autovacuum_vacuum_scale_factor = 0.2
            );
            ALTER TABLE marketplace_userprofileknowledgenumerical SET (
                autovacuum_analyze_scale_factor = 0.01, autovacuum_analyze_threshold = 50000, autovacuum_vacuum_scale_factor = 0.2
            );
            ALTER TABLE marketplace_userprofileknowledgetext SET (
                autovacuum_analyze_scale_factor = 0.01, autovacuum_analyze_threshold = 50000, autovacuum_vacuum_scale_factor = 0.2
            );
            
            ALTER TABLE thl_wall SET (
                autovacuum_analyze_scale_factor = 0.002, autovacuum_analyze_threshold = 10000,
                autovacuum_vacuum_scale_factor = 0.02, autovacuum_vacuum_threshold = 5000,
                fillfactor = 85
            );
            ALTER TABLE thl_session SET (
                autovacuum_analyze_scale_factor = 0.002, autovacuum_analyze_threshold = 10000,
                autovacuum_vacuum_scale_factor = 0.02, autovacuum_vacuum_threshold = 5000,
                fillfactor = 85
            );
            ALTER TABLE thl_user SET (
                autovacuum_analyze_scale_factor = 0.002, autovacuum_analyze_threshold = 10000,
                autovacuum_vacuum_scale_factor = 0.02, autovacuum_vacuum_threshold = 5000,
                fillfactor = 85
            );
            ALTER TABLE marketplace_surveystat SET (
                autovacuum_analyze_scale_factor = 0.01, autovacuum_analyze_threshold = 50000,
                autovacuum_vacuum_scale_factor = 0.02, autovacuum_vacuum_threshold = 50000,
                fillfactor = 60
            );
            """,
        ),
    ]
