# Generated by Django 6.0 on 2026-01-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thl_django", "0007_table_params"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="explanation_fragment_template",
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="explanation_template",
            field=models.TextField(max_length=255, null=True),
        ),
    ]
