# Generated by Django 6.1 on 2026-09-01 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "thl_django",
            "0009_toolrun_mtrhop_portscanport_iplabel_mtr_portscan_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierPayout",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("ext_ref_id", models.CharField(max_length=64, unique=True)),
                ("business_id", models.UUIDField(null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("amount", models.BigIntegerField()),
                ("status", models.CharField(max_length=20, null=True)),
                ("payout_type", models.CharField(max_length=14)),
                ("request_data", models.JSONField(null=True)),
                ("order_data", models.JSONField(null=True)),
            ],
            options={
                "db_table": "supplier_payout",
                "indexes": [
                    models.Index(
                        fields=["created"], name="supplier_pa_created_336236_idx"
                    ),
                    models.Index(
                        fields=["business_id"], name="supplier_pa_busines_2c7a4e_idx"
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="payout",
            name="supplier_payout",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="thl_django.supplierpayout",
            ),
        ),
    ]
