# Generated by Django 6.1 on 2026-08-31 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thl_django', '0009_toolrun_mtrhop_portscanport_iplabel_mtr_portscan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thlusermetadata',
            name='display_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
