# Generated by Django 6.1.1 on 2026-09-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thl_django', '0011_supplierpayout_payout_supplier_payout'),
    ]

    operations = [
        migrations.AddField(
            model_name='thlusermetadata',
            name='canonical_email',
            field=models.CharField(max_length=320, null=True),
        ),
        migrations.AddIndex(
            model_name='thlusermetadata',
            index=models.Index(fields=['canonical_email'], name='thl_usermet_canonic_141d0f_idx'),
        ),
    ]
