# Generated by Django 6.1.1 on 2026-10-08 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thl_django', '0012_thlusermetadata_canonical_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokerageproduct',
            name='balance',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='brokerageproduct',
            name='balance_net_7d',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='brokerageproduct',
            name='payouts',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='brokerageproduct',
            name='pop_financial',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='brokerageproduct',
            name='task_completes_7d',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='brokerageproduct',
            name='user_wallet_balance',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='brokerageproduct',
            name='users_active_7d',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
